sudo: false

language: java

jdk:
  - oraclejdk8

env:
  - OPENCGA_HOME=$TRAVIS_BUILD_DIR/opencga/opencga-app/build MONGODB_VERSION=3.0.4

before_install:
  - chmod +x install-dependencies.sh

install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - ./install-dependencies.sh
  - mongod --version

script:
  - mvn install -B
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)

